-- Migration 009: Seed plant database
-- Calibrated for Kildare, Ireland (last frost ~April 20, first frost ~October 30)
-- Month numbers: 1=January through 12=December (1-indexed, NOT 0-indexed)
-- RHS hardiness scale used throughout

-- ────────────────────────────────────────────────────────────
-- VEGETABLES
-- ────────────────────────────────────────────────────────────

INSERT INTO plants (
  name, latin_name, category, subcategory, description,
  sow_indoors_start, sow_indoors_end,
  sow_outdoors_start, sow_outdoors_end,
  transplant_start, transplant_end,
  harvest_start, harvest_end,
  weeks_indoors_min, weeks_indoors_max,
  germination_days_min, germination_days_max,
  germination_temp_min, germination_temp_max,
  spacing_cm, row_spacing_cm, sowing_depth_cm,
  height_cm_min, height_cm_max,
  sun_requirement, water_needs, soil_preference,
  hardiness_zone, frost_tolerant, frost_tender, slug_risk,
  succession_sow,
  companion_plants, avoid_near,
  common_pests, common_diseases,
  notes, growing_tips
) VALUES

-- ONION
('Onion', 'Allium cepa', 'vegetable', 'allium',
 'A kitchen staple. Grow from seed or sets. Sets are easier for beginners.',
 1, 3, NULL, NULL, 4, 5, 7, 9,
 10, 12,
 10, 21, 10, 24,
 10, 30, 1.0,
 30, 45,
 'full_sun', 'medium', 'well-drained, fertile',
 'H4', true, false, 'low',
 false,
 ARRAY['carrot', 'lettuce', 'beetroot'], ARRAY['bean', 'pea'],
 ARRAY['onion fly', 'thrips'], ARRAY['white rot', 'downy mildew'],
 'Sow in January–February indoors. Plant sets in March–April outdoors. Harvest when tops yellow and fall over.',
 'Ensure good drainage to prevent white rot. Avoid planting where alliums grew in last 3 years.'),

-- LEEK
('Leek', 'Allium porrum', 'vegetable', 'allium',
 'A cool-season staple for Irish winters. Hardier than onions.',
 1, 3, NULL, NULL, 6, 7, 10, 3,
 14, 16,
 14, 21, 10, 20,
 15, 15, 1.5,
 45, 60,
 'full_sun', 'medium', 'fertile, moisture-retentive',
 'H5', true, false, 'low',
 false,
 ARRAY['carrot', 'celery'], ARRAY['bean', 'pea'],
 ARRAY['leek moth', 'thrips'], ARRAY['leek rust', 'white rot'],
 'Sow in seed trays in Jan–March. Transplant to deep holes (pencil-dibbed) in June–July. Harvest from October through winter.',
 'Deep planting blanches the stems. Earth up as plants grow to extend the white shaft.'),

-- POTATO (EARLY)
('Potato (First Early)', 'Solanum tuberosum', 'vegetable', 'root_veg',
 'First early potatoes like Charlotte or Rocket. Ready in 10–12 weeks. Chit from February.',
 NULL, NULL, 3, 4, NULL, NULL, 6, 8,
 NULL, NULL,
 NULL, NULL, NULL, NULL,
 30, 60, 10.0,
 50, 70,
 'full_sun', 'medium', 'loose, fertile, well-drained',
 'H3', false, true, 'medium',
 false,
 ARRAY['horseradish', 'marigold'], ARRAY['tomato', 'fennel', 'cucumber'],
 ARRAY['aphid', 'wireworm', 'slugs'], ARRAY['blight', 'scab', 'blackleg'],
 'Chit in egg boxes from February in a cool bright frost-free place. Plant out late March–April when risk of hard frost is reduced.',
 'Earth up stems as they grow to prevent greening. Watch for blight from June — spray with Bordeaux mixture if needed.'),

-- POTATO (MAINCROP)
('Potato (Maincrop)', 'Solanum tuberosum', 'vegetable', 'root_veg',
 'Maincrop potatoes like Rooster, Kerr''s Pink, or King Edward. Needs a longer season.',
 NULL, NULL, 4, 5, NULL, NULL, 8, 10,
 NULL, NULL,
 NULL, NULL, NULL, NULL,
 40, 75, 10.0,
 60, 90,
 'full_sun', 'medium', 'loose, fertile, well-drained',
 'H3', false, true, 'medium',
 false,
 ARRAY['horseradish', 'marigold'], ARRAY['tomato', 'fennel', 'cucumber'],
 ARRAY['aphid', 'wireworm', 'slugs'], ARRAY['blight', 'scab', 'blackleg'],
 'Plant from mid-April to May. Chit from late February. Harvest after foliage dies back, usually August–October.',
 'Rooster is an excellent Irish maincrop with good blight resistance. Store in paper sacks in a cool dark frost-free shed.'),

-- TOMATO
('Tomato', 'Solanum lycopersicum', 'vegetable', 'fruiting',
 'Grow in a polytunnel or greenhouse in Ireland — outdoor crops are too unreliable in Kildare.',
 2, 3, NULL, NULL, 5, 6, 7, 10,
 8, 10,
 7, 14, 18, 25,
 45, 45, 0.5,
 100, 180,
 'full_sun', 'high', 'rich, well-drained',
 'H1c', false, true, 'low',
 false,
 ARRAY['basil', 'marigold', 'carrot'], ARRAY['fennel', 'potato', 'brassica'],
 ARRAY['aphid', 'whitefly', 'red spider mite'], ARRAY['blight', 'botrytis', 'blossom end rot'],
 'Sow in a heated propagator (18–25°C) from late February. Never plant outdoors before mid-May in Kildare.',
 'Feed weekly with high-potash tomato feed once flowers form. Pinch out sideshoots on cordon varieties. Ventilate polytunnel to reduce humidity.'),

-- CARROT
('Carrot', 'Daucus carota', 'vegetable', 'root_veg',
 'Direct sow only — carrots hate being transplanted. Needs loose, stone-free soil.',
 NULL, NULL, 3, 7, NULL, NULL, 6, 10,
 NULL, NULL,
 14, 21, 7, 24,
 5, 30, 0.5,
 20, 30,
 'full_sun', 'low', 'deep, loose, stone-free, well-drained',
 'H5', true, false, 'low',
 true,
 ARRAY['onion', 'leek', 'rosemary', 'chive'], ARRAY['dill', 'parsnip'],
 ARRAY['carrot fly'], ARRAY['cavity spot'],
 'Sow thinly in rows. Thin to 5cm when large enough. Cover with fleece to prevent carrot fly (lays eggs attracted by smell when thinning).',
 'Sow from March to July for succession. Nantes types good for Kildare soil. Avoid fresh manure — causes forking.'),

-- PARSNIP
('Parsnip', 'Pastinaca sativa', 'vegetable', 'root_veg',
 'Slow to germinate but very hardy. Improved by frost — great Irish winter veg.',
 NULL, NULL, 3, 4, NULL, NULL, 10, 3,
 NULL, NULL,
 21, 28, 10, 20,
 15, 30, 1.0,
 30, 40,
 'full_sun', 'low', 'deep, loose, stone-free',
 'H6', true, false, 'low',
 false,
 ARRAY['pea', 'radish'], ARRAY['carrot'],
 ARRAY['carrot fly', 'celery fly'], ARRAY['canker'],
 'Sow fresh seed each year — old seed germinates poorly. Cover with fleece early in season. Leave in ground through winter.',
 'Pre-germinate seeds on damp paper towel for better strike rate. Frost sweetens the roots.'),

-- COURGETTE
('Courgette', 'Cucurbita pepo', 'vegetable', 'fruiting',
 'Very productive in Ireland once summer arrives. Harvest young (15–20cm) for best flavour.',
 4, 5, NULL, NULL, 5, 6, 6, 10,
 4, 6,
 7, 14, 18, 30,
 90, 90, 2.5,
 60, 100,
 'full_sun', 'high', 'rich, moisture-retentive',
 'H2', false, true, 'high',
 false,
 ARRAY['nasturtium', 'marigold'], ARRAY['potato'],
 ARRAY['slugs', 'vine weevil'], ARRAY['powdery mildew', 'botrytis'],
 'Sow indoors in April. Plant out after last frost (mid-May). One or two plants produces plenty for a family.',
 'Water at base not leaves to reduce mildew. Slugs are a major pest — use nematodes or copper rings around young plants.'),

-- CABBAGE
('Cabbage', 'Brassica oleracea var. capitata', 'vegetable', 'brassica',
 'Classic Irish veg. Varieties for different seasons: spring, summer, and winter cabbage.',
 2, 4, NULL, NULL, 4, 6, 6, 12,
 6, 8,
 7, 12, 10, 20,
 45, 45, 1.0,
 30, 50,
 'full_sun', 'medium', 'firm, fertile, limed if acidic',
 'H5', true, false, 'high',
 false,
 ARRAY['dill', 'mint', 'thyme', 'rosemary'], ARRAY['strawberry', 'tomato'],
 ARRAY['cabbage white', 'slugs', 'aphid', 'cabbage root fly'], ARRAY['clubroot', 'ring spot'],
 'Net immediately after planting to prevent cabbage white butterfly. Firm soil well when planting to prevent cabbage heart rot.',
 'Lime soil if pH below 6.5 — clubroot thrives in acidic conditions. Never grow brassicas on same ground more than once in 3 years.'),

-- KALE
('Kale', 'Brassica oleracea var. acephala', 'vegetable', 'brassica',
 'One of the hardiest vegetables for Irish winters. Harvests from October through March.',
 3, 5, NULL, NULL, 6, 7, 10, 3,
 6, 8,
 7, 12, 10, 18,
 45, 45, 1.0,
 60, 90,
 'full_sun', 'medium', 'firm, fertile',
 'H6', true, false, 'high',
 false,
 ARRAY['dill', 'mint', 'hyssop'], ARRAY['strawberry'],
 ARRAY['cabbage white', 'slugs', 'aphid'], ARRAY['clubroot'],
 'Sow May–June for autumn/winter harvests. Pick outer leaves regularly. Improved by frost.',
 'Dwarf Curly Scots or Cavolo Nero are excellent choices for Kildare. Net against pigeons and butterflies.'),

-- CHARD / SWISS CHARD
('Chard (Swiss Chard)', 'Beta vulgaris subsp. vulgaris', 'vegetable', 'leafy',
 'Productive, colourful, and hardy. Harvests for months from one sowing.',
 3, 5, 4, 7, NULL, NULL, 6, 11,
 NULL, NULL,
 10, 14, 10, 20,
 30, 30, 2.0,
 40, 60,
 'full_sun', 'medium', 'fertile, moisture-retentive',
 'H5', true, false, 'high',
 true,
 ARRAY['allium', 'brassica'], ARRAY['spinach'],
 ARRAY['slugs', 'aphid'], ARRAY['leaf spot', 'downy mildew'],
 'Direct sow from April. Pick outer leaves regularly to encourage new growth. Will overwinter in mild years.',
 'Rainbow Chard is ornamental as well as edible. Sow successionally for year-round harvest.'),

-- BEETROOT
('Beetroot', 'Beta vulgaris subsp. vulgaris var. conditiva', 'vegetable', 'root_veg',
 'Easy to grow, great in an Irish kitchen. Bolt-resistant varieties for early sowing.',
 3, 4, 4, 7, NULL, NULL, 6, 10,
 NULL, NULL,
 10, 14, 10, 20,
 10, 30, 2.0,
 25, 35,
 'full_sun', 'medium', 'fertile, well-drained',
 'H4', false, false, 'medium',
 true,
 ARRAY['onion', 'lettuce', 'kohlrabi'], ARRAY['runner_bean'],
 ARRAY['slugs', 'aphid'], ARRAY['leaf spot', 'boron deficiency'],
 'Sow bolt-resistant varieties (Boltardy) from March. Thin to 10cm. Leaves edible too.',
 'Sow every 3 weeks from April for succession. Each "seed" is actually a cluster — expect 2–3 seedlings per station, thin to one.'),

-- LETTUCE
('Lettuce', 'Lactuca sativa', 'vegetable', 'leafy',
 'Ideal for cut-and-come-again harvesting. Needs moisture and bolts in heat.',
 2, 4, 4, 8, 4, 7, 5, 10,
 4, 6,
 7, 14, 10, 20,
 20, 25, 0.5,
 20, 35,
 'partial_shade', 'medium', 'fertile, moisture-retentive',
 'H4', false, false, 'high',
 true,
 ARRAY['carrot', 'radish', 'chive', 'beetroot'], ARRAY['celery'],
 ARRAY['slugs', 'aphid', 'lettuce root aphid'], ARRAY['downy mildew', 'grey mould'],
 'Sow every 3 weeks for continuous supply. Avoid sowing in midsummer heat — bolts. Partial shade in July helps.',
 'Loose-leaf varieties (Salad Bowl, Oak Leaf) are more productive than hearting types. Never let soil dry out.'),

-- SPINACH
('Spinach', 'Spinacia oleracea', 'vegetable', 'leafy',
 'Quick to grow, bolts in heat. Better suited to spring and autumn growing in Ireland.',
 NULL, NULL, 3, 5, NULL, NULL, 4, 6,
 NULL, NULL,
 7, 14, 7, 18,
 15, 30, 2.0,
 20, 30,
 'partial_shade', 'medium', 'fertile, moisture-retentive',
 'H4', true, false, 'high',
 true,
 ARRAY['strawberry', 'pea'], ARRAY['chard'],
 ARRAY['slugs', 'aphid'], ARRAY['downy mildew'],
 'Sow March–April and August–September. Bolts rapidly in summer. Autumn sowings overwinter for early spring harvest.',
 'Use perpetual spinach (which is actually chard) for summer cropping — it''s more bolt-resistant.'),

-- PEAS
('Peas', 'Pisum sativum', 'vegetable', 'legume',
 'One of the first outdoor sowings of the year. Sweet, tender, and very Irish-garden-appropriate.',
 2, 3, 3, 5, NULL, NULL, 6, 8,
 NULL, NULL,
 7, 14, 7, 18,
 7, 15, 3.0,
 60, 120,
 'full_sun', 'medium', 'well-drained, fertile',
 'H5', true, false, 'high',
 true,
 ARRAY['carrot', 'turnip', 'radish', 'mint'], ARRAY['onion', 'garlic', 'shallot'],
 ARRAY['pea moth', 'slugs', 'mice', 'aphid'], ARRAY['powdery mildew', 'fusarium'],
 'Sow direct from March in Kildare when soil reaches 10°C. Protect from mice early on. Provide support for climbing types.',
 'Mangetout and sugar snap are easier to pick than shelling peas. Sow in batches 3 weeks apart for succession.'),

-- BROAD BEAN
('Broad Bean', 'Vicia faba', 'vegetable', 'legume',
 'Hardy and early. Can be sown in autumn for an early crop, or direct sow from February.',
 NULL, NULL, 2, 4, NULL, NULL, 6, 7,
 NULL, NULL,
 7, 14, 7, 15,
 25, 25, 5.0,
 60, 120,
 'full_sun', 'medium', 'well-drained, fertile',
 'H5', true, false, 'medium',
 false,
 ARRAY['brassica', 'carrot', 'beet', 'potato'], ARRAY['onion', 'fennel'],
 ARRAY['black bean aphid', 'slugs', 'mice'], ARRAY['chocolate spot', 'rust'],
 'Sow from February outdoors in Kildare, or October for overwintering (protect with fleece in hard frost).',
 'Pinch out growing tips when first pods set — reduces blackfly and encourages pod development.'),

-- FRENCH BEAN
('French Bean', 'Phaseolus vulgaris', 'vegetable', 'legume',
 'Tender. No frost tolerance at all. Sow after last frost or start indoors.',
 4, 5, 5, 6, 5, 6, 7, 9,
 3, 4,
 7, 14, 16, 24,
 20, 30, 5.0,
 40, 50,
 'full_sun', 'medium', 'well-drained, fertile',
 'H1c', false, true, 'medium',
 true,
 ARRAY['carrot', 'cucumber', 'cabbage', 'summer_savory'], ARRAY['onion', 'fennel', 'beet'],
 ARRAY['slugs', 'aphid', 'bean weevil'], ARRAY['halo blight', 'botrytis'],
 'Sow after last frost (mid-May in Kildare) or start indoors in April. Harvest regularly to prolong cropping.',
 'Climbing varieties more productive than dwarf. Don''t overwater before flowers form.'),

-- RUNNER BEAN
('Runner Bean', 'Phaseolus coccineus', 'vegetable', 'legume',
 'Very productive once established. Attractive flowers too. Needs tall supports.',
 4, 5, 5, 6, 5, 6, 7, 10,
 4, 6,
 10, 14, 16, 24,
 15, 60, 5.0,
 200, 300,
 'full_sun', 'high', 'deep, moisture-retentive, fertile',
 'H2', false, true, 'medium',
 false,
 ARRAY['summer_savory', 'marigold', 'carrot', 'cucumber'], ARRAY['onion', 'fennel'],
 ARRAY['slugs', 'aphid', 'bean weevil'], ARRAY['halo blight', 'botrytis'],
 'Build strong supports (2m+) before sowing. Mist flowers in dry weather to help pod set.',
 'Soak seeds overnight before sowing to improve germination. Harvest every few days to keep producing.'),

-- GARLIC
('Garlic', 'Allium sativum', 'vegetable', 'allium',
 'Plant autumn cloves for a summer harvest. Far better results than spring-planted garlic in Ireland.',
 NULL, NULL, 9, 11, NULL, NULL, 6, 8,
 NULL, NULL,
 NULL, NULL, NULL, NULL,
 15, 30, 5.0,
 30, 60,
 'full_sun', 'low', 'well-drained, fertile',
 'H5', true, false, 'low',
 false,
 ARRAY['rose', 'tomato', 'carrot', 'beetroot'], ARRAY['bean', 'pea'],
 ARRAY['onion fly', 'eelworm'], ARRAY['white rot', 'rust', 'downy mildew'],
 'Plant individual cloves in September–October, pointed end up, 5cm deep. Harvest when lower leaves yellow (June–August).',
 'Hardneck varieties (Chesnok, Marino) have better flavour but shorter shelf life than softneck. Dry well after harvest.'),

-- SHALLOT
('Shallot', 'Allium cepa var. aggregatum', 'vegetable', 'allium',
 'Easy from sets. One bulb multiplies to a cluster of 8–12 shallots.',
 NULL, NULL, 2, 4, NULL, NULL, 7, 8,
 NULL, NULL,
 NULL, NULL, NULL, NULL,
 15, 25, 2.0,
 30, 45,
 'full_sun', 'low', 'well-drained, fertile',
 'H5', true, false, 'low',
 false,
 ARRAY['carrot', 'lettuce', 'tomato'], ARRAY['bean', 'pea'],
 ARRAY['onion fly', 'thrips'], ARRAY['white rot', 'downy mildew'],
 'Plant sets from February when soil is workable. Push into soil with tip just showing. Harvest in July.',
 'Excellent for overwintering — plant in autumn for earlier crop. Dry thoroughly before storing.'),

-- BROCCOLI
('Broccoli (Calabrese)', 'Brassica oleracea var. italica', 'vegetable', 'brassica',
 'Fast-growing summer broccoli. Cut central head then side shoots continue producing.',
 3, 5, 5, 6, 5, 6, 7, 9,
 6, 8,
 7, 12, 7, 20,
 30, 45, 1.0,
 60, 80,
 'full_sun', 'medium', 'firm, fertile, limed',
 'H4', true, false, 'high',
 false,
 ARRAY['dill', 'mint', 'rosemary', 'thyme'], ARRAY['tomato', 'strawberry'],
 ARRAY['cabbage white', 'slugs', 'aphid', 'cabbage root fly'], ARRAY['clubroot', 'ring spot'],
 'Sow indoors March–May. Transplant May–June. Firm soil well. Net against butterflies immediately.',
 'Harvest central head before it flowers. Side shoots produce for several weeks. Eat fresh — doesn''t store well.'),

-- CAULIFLOWER
('Cauliflower', 'Brassica oleracea var. botrytis', 'vegetable', 'brassica',
 'Challenging but rewarding. Needs consistent moisture and firm ground. Very popular in Irish cooking.',
 2, 4, NULL, NULL, 4, 6, 7, 11,
 6, 8,
 7, 12, 10, 20,
 60, 60, 1.0,
 60, 80,
 'full_sun', 'high', 'firm, very fertile, limed, moisture-retentive',
 'H5', true, false, 'high',
 false,
 ARRAY['dill', 'mint', 'sage'], ARRAY['tomato', 'strawberry'],
 ARRAY['cabbage white', 'slugs', 'aphid', 'cabbage root fly'], ARRAY['clubroot', 'downy mildew'],
 'Very hungry and thirsty plant. Never let it dry out or curds will be poor. Tie leaves over curd to keep it white.',
 'Autumn Monarch or Walcheren varieties suit Irish conditions. More reliable than summer types.'),

-- CUCUMBER
('Cucumber', 'Cucumis sativus', 'vegetable', 'fruiting',
 'Grow in polytunnel or greenhouse in Ireland. Not suited to outdoor growing in Kildare.',
 4, 5, NULL, NULL, 5, 6, 7, 9,
 4, 6,
 7, 14, 20, 30,
 60, 60, 1.0,
 150, 200,
 'full_sun', 'high', 'rich, well-drained, moisture-retentive',
 'H1c', false, true, 'low',
 false,
 ARRAY['bean', 'pea', 'sunflower', 'marigold'], ARRAY['potato', 'aromatic_herbs'],
 ARRAY['red spider mite', 'whitefly', 'aphid'], ARRAY['powdery mildew', 'cucumber mosaic virus'],
 'Sow April in heat (20°C+). Plant in polytunnel after hardening off. All-female varieties (fewer bitter fruits).',
 'Keep well ventilated and watered. Mist in heat to deter spider mite. Feed weekly once fruiting.'),

-- COURGETTE (already added) so do Pumpkin/Squash
('Pumpkin / Squash', 'Cucurbita maxima', 'vegetable', 'fruiting',
 'Large, productive plants needing space. Leave to mature on vine for storage.',
 4, 5, NULL, NULL, 5, 6, 9, 10,
 4, 6,
 7, 14, 18, 30,
 90, 150, 2.5,
 30, 50,
 'full_sun', 'high', 'rich, moisture-retentive',
 'H1c', false, true, 'high',
 false,
 ARRAY['marigold', 'nasturtium', 'sweetcorn', 'bean'], ARRAY['potato'],
 ARRAY['slugs', 'vine weevil'], ARRAY['powdery mildew', 'botrytis'],
 'Needs plenty of space and warmth. Grows well in a compost heap. Cure harvested fruits in sun to harden skin.',
 'Irish summers are often cool for pumpkins — choose smaller varieties or grow under fleece early on.'),

-- SWEETCORN
('Sweetcorn', 'Zea mays', 'vegetable', 'other',
 'Possible in Ireland in a sheltered spot or polytunnel. Wind-pollinated — plant in blocks not rows.',
 4, 5, NULL, NULL, 5, 6, 8, 9,
 4, 6,
 7, 10, 16, 24,
 40, 40, 3.0,
 150, 200,
 'full_sun', 'medium', 'fertile, well-drained, sheltered',
 'H2', false, true, 'medium',
 false,
 ARRAY['pumpkin', 'bean', 'nasturtium'], ARRAY['tomato'],
 ARRAY['frit fly', 'slugs', 'birds'], ARRAY['smut'],
 'Start indoors in April in pots (sweetcorn hates root disturbance). Plant in block minimum 4×4 for wind pollination.',
 'Test for ripeness: silk turns brown + squeeze a kernel — milky liquid means ripe. Irish summers borderline for this crop.'),

-- CELERY
('Celery', 'Apium graveolens', 'vegetable', 'other',
 'Demanding but very rewarding. Needs consistent moisture and a long season.',
 2, 3, NULL, NULL, 5, 6, 9, 11,
 10, 12,
 14, 21, 15, 20,
 30, 30, 0.3,
 30, 60,
 'full_sun', 'high', 'very fertile, moisture-retentive, rich in organic matter',
 'H3', false, false, 'medium',
 false,
 ARRAY['leek', 'tomato', 'bean', 'cabbage'], ARRAY['carrot', 'parsnip'],
 ARRAY['celery fly', 'slugs', 'aphid'], ARRAY['leaf spot', 'heart rot'],
 'Sow very thinly on surface of compost — tiny seeds need light to germinate. Self-blanching types easier.',
 'Never let it dry out. Grows best in a wet Irish summer. Use trenched varieties for better flavour.'),

-- FENNEL (FLORENCE)
('Fennel (Florence)', 'Foeniculum vulgare var. azoricum', 'vegetable', 'other',
 'Grow for the bulb, not leaves. Bolt-resistant varieties essential for Irish growing.',
 NULL, NULL, 5, 7, NULL, NULL, 8, 10,
 NULL, NULL,
 7, 14, 15, 22,
 30, 30, 0.5,
 30, 60,
 'full_sun', 'medium', 'well-drained, fertile',
 'H3', false, false, 'low',
 false,
 ARRAY['none'], ARRAY['carrot', 'tomato', 'bean', 'pea', 'coriander'],
 ARRAY['aphid', 'slugs'], ARRAY['powdery mildew'],
 'Bolt-resistant variety essential (Romanesco, Perfection). Sow direct from May. Earth up bulb as it develops.',
 'Fennel inhibits growth of nearby plants — keep isolated in the bed. Harvest before bulbs go to seed.'),

-- CUCUMBER already above — skip to herbs

-- ────────────────────────────────────────────────────────────
-- HERBS
-- ────────────────────────────────────────────────────────────

-- PARSLEY
('Parsley', 'Petroselinum crispum', 'herb', NULL,
 'Biennial but usually grown as annual. Slow to germinate — be patient.',
 2, 4, 4, 6, NULL, NULL, 6, 11,
 8, 10,
 21, 28, 15, 22,
 15, 20, 0.5,
 30, 60,
 'partial_shade', 'medium', 'fertile, moisture-retentive',
 'H4', true, false, 'low',
 true,
 ARRAY['tomato', 'asparagus', 'rose'], ARRAY['onion', 'garlic'],
 ARRAY['aphid', 'carrot fly'], ARRAY['leaf spot'],
 'Sow Feb–April indoors or direct from April. Germinates slowly — can take 4+ weeks. Pour boiling water in drill to help.',
 'Flat-leaf varieties have better flavour. Keep cut to prevent bolting. Overwinters under fleece in mild Kildare winters.'),

-- CORIANDER
('Coriander', 'Coriandrum sativum', 'herb', NULL,
 'Bolts quickly in heat. Sow little and often in cool periods for leaf harvest.',
 NULL, NULL, 3, 9, NULL, NULL, 5, 10,
 NULL, NULL,
 14, 21, 15, 20,
 15, 20, 0.5,
 20, 60,
 'full_sun', 'low', 'well-drained',
 'H1c', false, true, 'low',
 true,
 ARRAY['spinach', 'dill', 'chervil'], ARRAY['fennel'],
 ARRAY['aphid', 'whitefly'], ARRAY['powdery mildew'],
 'Sow every 3 weeks for continuous supply. Slow-bolt varieties (Cruiser, Calypso) much better. Sow direct.',
 'Coriander loves cool conditions — ideal for Irish spring and autumn. Let some bolt for seeds.'),

-- BASIL
('Basil', 'Ocimum basilicum', 'herb', NULL,
 'Needs warmth. Best in a polytunnel or south-facing windowsill in Ireland.',
 3, 5, NULL, NULL, 5, 6, 6, 9,
 6, 8,
 7, 14, 18, 25,
 20, 25, 0.5,
 30, 60,
 'full_sun', 'medium', 'well-drained, fertile',
 'H1c', false, true, 'medium',
 true,
 ARRAY['tomato', 'pepper'], ARRAY['sage'],
 ARRAY['aphid', 'slug'], ARRAY['fusarium', 'downy mildew'],
 'Sow in heat (20°C+). Water at base — hates wet leaves. Pinch flowers to prolong leaf harvest.',
 'Genovese for cooking, Purple Ruffles for ornament. Keep above 10°C — dies below.'),

-- CHIVE
('Chive', 'Allium schoenoprasum', 'herb', NULL,
 'Hardy perennial. Very easy to grow. Attractive purple flowers good for pollinators.',
 2, 4, 3, 5, NULL, NULL, 4, 10,
 NULL, NULL,
 14, 21, 10, 20,
 15, 20, 0.5,
 20, 30,
 'full_sun', 'low', 'well-drained',
 'H6', true, false, 'low',
 false,
 ARRAY['carrot', 'tomato', 'apple'], ARRAY['bean', 'pea'],
 ARRAY['aphid', 'thrips'], ARRAY['onion white rot'],
 'Perennial. Cut back hard after flowering to encourage fresh growth. Divide clumps every 3 years.',
 'Garlic chives (A. tuberosum) have flatter leaves and white flowers — also worth growing.'),

-- MINT
('Mint', 'Mentha spp.', 'herb', NULL,
 'Very vigorous — contains in a pot or buried bucket to stop it taking over.',
 NULL, NULL, NULL, NULL, 4, 5, 5, 10,
 NULL, NULL,
 14, 21, 10, 24,
 45, 45, 0.5,
 30, 60,
 'partial_shade', 'medium', 'moisture-retentive',
 'H6', true, false, 'low',
 false,
 ARRAY['tomato', 'pea', 'brassica'], ARRAY['parsley'],
 ARRAY['aphid', 'mint beetle'], ARRAY['rust', 'powdery mildew'],
 'Propagate from divisions or runners rather than seed. Spearmint and peppermint most useful.',
 'Grow in a large pot sunk into the ground to contain roots. Harvest young growth for best flavour.'),

-- THYME
('Thyme', 'Thymus vulgaris', 'herb', NULL,
 'Hardy Mediterranean herb that thrives in Ireland. Excellent for bees.',
 2, 4, NULL, NULL, 5, 6, 5, 10,
 8, 10,
 14, 28, 18, 25,
 20, 30, 0.5,
 15, 30,
 'full_sun', 'low', 'well-drained, gritty',
 'H5', true, false, 'low',
 false,
 ARRAY['cabbage', 'broccoli', 'rose'], ARRAY['none'],
 ARRAY['aphid'], ARRAY['root rot (in wet soil)'],
 'Drought-tolerant once established. Cut back hard in spring. Good in rock gardens and containers.',
 'Common thyme most useful. Lemon thyme also excellent. Propagate from cuttings in summer.'),

-- ROSEMARY
('Rosemary', 'Salvia rosmarinus', 'herb', NULL,
 'Woody perennial. Needs good drainage — Ireland''s wet winters can cause root rot.',
 NULL, NULL, NULL, NULL, 4, 6, 4, 10,
 NULL, NULL,
 21, 28, 16, 22,
 45, 60, 0.5,
 60, 150,
 'full_sun', 'low', 'very well-drained, gritty, sheltered',
 'H4', true, false, 'low',
 false,
 ARRAY['sage', 'thyme', 'lavender', 'cabbage', 'bean'], ARRAY['none'],
 ARRAY['rosemary beetle'], ARRAY['root rot in wet soils'],
 'Plant in very well-drained spot or raised bed. South or west-facing wall ideal. Can suffer in wet Kildare winters.',
 'Take semi-ripe cuttings in summer. Miss Jessopp''s Upright and Tuscan Blue are reliable outdoor varieties for Ireland.'),

-- SAGE
('Sage', 'Salvia officinalis', 'herb', NULL,
 'Hardy shrubby herb. Long-lived once established. Excellent with pork and poultry.',
 2, 3, NULL, NULL, 4, 6, 5, 10,
 8, 10,
 14, 21, 15, 20,
 45, 60, 0.5,
 45, 75,
 'full_sun', 'low', 'well-drained',
 'H5', true, false, 'low',
 false,
 ARRAY['rosemary', 'brassica', 'carrot'], ARRAY['cucumber', 'onion'],
 ARRAY['capsid bug', 'rosemary beetle'], ARRAY['powdery mildew'],
 'Prune in spring to prevent woodiness. Take cuttings to replace old plants every 5–6 years.',
 'Purple sage (Salvia officinalis Purpurascens) is ornamental and culinary. Very reliable in Irish gardens.');

-- ────────────────────────────────────────────────────────────
-- CUT FLOWERS
-- ────────────────────────────────────────────────────────────

INSERT INTO plants (
  name, latin_name, category, subcategory, description,
  sow_indoors_start, sow_indoors_end,
  sow_outdoors_start, sow_outdoors_end,
  transplant_start, transplant_end,
  harvest_start, harvest_end,
  weeks_indoors_min, weeks_indoors_max,
  germination_days_min, germination_days_max,
  germination_temp_min, germination_temp_max,
  spacing_cm, row_spacing_cm, sowing_depth_cm,
  height_cm_min, height_cm_max,
  sun_requirement, water_needs, soil_preference,
  hardiness_zone, frost_tolerant, frost_tender, slug_risk,
  is_cut_flower, vase_life_days, succession_sow, succession_interval_weeks,
  companion_plants, avoid_near,
  common_pests, common_diseases,
  notes, growing_tips
) VALUES

-- SWEET PEA
('Sweet Pea', 'Lathyrus odoratus', 'flower', 'cut_flower',
 'The classic Irish cottage garden flower. Wonderfully fragrant. Sow late autumn or early spring.',
 1, 3, 3, 4, 4, 5, 6, 9,
 10, 14,
 14, 21, 15, 20,
 20, 30, 3.0,
 150, 200,
 'full_sun', 'medium', 'deep, fertile, moisture-retentive',
 'H5', true, false, 'medium',
 true, 10, true, 3,
 ARRAY['carrot', 'radish'], ARRAY['onion', 'garlic'],
 ARRAY['aphid', 'slugs', 'mice'], ARRAY['powdery mildew', 'botrytis'],
 'Sow in tubes (toilet roll inners) in Jan–March or direct outdoors in April. Nick or soak seeds for better germination.',
 'Pick flowers regularly to keep producing. Never let pods set or flowering stops. Spencer varieties are most fragrant.'),

-- SUNFLOWER
('Sunflower', 'Helianthus annuus', 'flower', 'cut_flower',
 'Easy, cheerful, and very productive. Branching varieties best for cut flowers.',
 3, 4, 4, 5, 5, 6, 7, 9,
 4, 6,
 7, 14, 18, 25,
 30, 45, 2.5,
 100, 200,
 'full_sun', 'low', 'well-drained, any reasonably fertile',
 'H2', false, true, 'high',
 true, 7, true, 3,
 ARRAY['cucumber', 'tomato'], ARRAY['potato'],
 ARRAY['slugs', 'birds', 'aphid'], ARRAY['downy mildew', 'botrytis'],
 'Direct sow or start indoors in April. Branching varieties (Velvet Queen, ProCut series) give more stems.',
 'Protect seedlings from slugs. Harvest when petals just start to open for best vase life.'),

-- ZINNIA
('Zinnia', 'Zinnia elegans', 'flower', 'cut_flower',
 'Bright, long-lasting cut flower. Needs warmth — polytunnel or sheltered spot in Ireland.',
 4, 5, NULL, NULL, 5, 6, 7, 10,
 4, 6,
 7, 14, 20, 28,
 20, 30, 0.5,
 45, 90,
 'full_sun', 'medium', 'well-drained, fertile',
 'H1c', false, true, 'high',
 true, 10, true, 3,
 ARRAY['marigold', 'dahlia'], ARRAY['none'],
 ARRAY['slugs', 'aphid'], ARRAY['powdery mildew', 'alternaria'],
 'Needs warmth to thrive. Start indoors in April. Water at base to reduce mildew. Pinch out growing tip early for bushier plants.',
 'Benary''s Giant series are best for cut flowers. Avoid wetting foliage.'),

-- COSMOS
('Cosmos', 'Cosmos bipinnatus', 'flower', 'cut_flower',
 'Airy, elegant annual. Very productive. Perfect for Irish summer gardens.',
 3, 5, 4, 5, 5, 6, 7, 10,
 6, 8,
 7, 14, 15, 25,
 30, 45, 0.5,
 60, 120,
 'full_sun', 'low', 'well-drained, not too rich',
 'H2', false, true, 'medium',
 true, 7, true, 4,
 ARRAY['marigold', 'zinnia'], ARRAY['none'],
 ARRAY['slugs', 'aphid'], ARRAY['botrytis'],
 'Easy from seed. Direct sow from April or start indoors from March. Pinch out to encourage branching.',
 'Don''t over-fertilise — too rich a soil produces leafy plants with fewer flowers. Excellent for pollinators.'),

-- DAHLIA
('Dahlia', 'Dahlia spp.', 'flower', 'cut_flower',
 'Prolific summer and autumn cut flower. Tubers need lifting before frost in Kildare.',
 NULL, NULL, NULL, NULL, 4, 5, 7, 10,
 NULL, NULL,
 NULL, NULL, NULL, NULL,
 30, 60, 10.0,
 45, 150,
 'full_sun', 'medium', 'rich, well-drained',
 'H3', false, true, 'medium',
 true, 7, false, NULL,
 ARRAY['tomato', 'marigold'], ARRAY['none'],
 ARRAY['slugs', 'earwig', 'aphid', 'vine weevil'], ARRAY['powdery mildew', 'virus', 'botrytis'],
 'Plant tubers in April–May after risk of hard frost. Lift and store in dry compost after first frost in October–November.',
 'Pinch out growing tip when 30cm tall for bushy plants. Harvest when bud just opening for best vase life. Remove spent blooms.'),

-- LUPIN
('Lupin', 'Lupinus polyphyllus', 'perennial', 'cut_flower',
 'Spectacular early summer flowers. Very popular in Irish cottage gardens.',
 1, 3, NULL, NULL, 4, 5, 5, 7,
 8, 12,
 14, 21, 15, 20,
 45, 60, 0.5,
 90, 150,
 'full_sun', 'low', 'well-drained, slightly acidic, not too rich',
 'H5', true, false, 'high',
 true, 5, false, NULL,
 ARRAY['brassica', 'carrot'], ARRAY['fennel'],
 ARRAY['slugs', 'aphid', 'lupin aphid'], ARRAY['powdery mildew', 'crown rot'],
 'Sow in pots Jan–March or buy plug plants. Nick seed coat before sowing to help germination.',
 'Remove flower spikes after blooming to encourage a second flush. Divide established clumps in spring every 3–4 years.'),

-- FOXGLOVE
('Foxglove', 'Digitalis purpurea', 'biennial', 'cut_flower',
 'Native Irish plant. Biennial — sow one year to flower the next. Wonderful and easy.',
 4, 6, 5, 7, 9, 10, 5, 7,
 NULL, NULL,
 14, 21, 15, 20,
 30, 45, 0.3,
 90, 150,
 'partial_shade', 'medium', 'any well-drained',
 'H6', true, false, 'low',
 true, 5, false, NULL,
 ARRAY['none'], ARRAY['none'],
 ARRAY['none'], ARRAY['powdery mildew'],
 'Biennial — sow in summer/autumn to flower the following year. Self-seeds prolifically. All parts toxic — wear gloves.',
 'Excelsior hybrids have flowers all the way around the spike. Excellent for partial shade under trees or hedges.'),

-- NIGELLA (Love-in-a-Mist)
('Nigella', 'Nigella damascena', 'annual', 'cut_flower',
 'Delicate, self-seeding annual. Both flowers and seed heads are valuable as cut material.',
 NULL, NULL, 3, 5, NULL, NULL, 5, 7,
 NULL, NULL,
 14, 21, 10, 20,
 15, 20, 0.5,
 40, 60,
 'full_sun', 'low', 'well-drained',
 'H5', true, false, 'low',
 true, 7, true, 3,
 ARRAY['none'], ARRAY['none'],
 ARRAY['aphid'], ARRAY['powdery mildew'],
 'Direct sow in autumn or early spring. Self-seeds freely once established. Use seed heads dried in arrangements.',
 'Doesn''t transplant well — sow direct. Miss Jekyll Blue is the classic variety. Hardy and reliable.'),

-- CORNFLOWER
('Cornflower', 'Centaurea cyanus', 'annual', 'cut_flower',
 'Brilliant blue hardy annual. Direct sow in autumn or spring. Great for cutting.',
 NULL, NULL, 3, 5, NULL, NULL, 5, 7,
 NULL, NULL,
 7, 14, 12, 18,
 15, 25, 0.5,
 30, 90,
 'full_sun', 'low', 'well-drained, not too rich',
 'H5', true, false, 'low',
 true, 7, true, 4,
 ARRAY['none'], ARRAY['none'],
 ARRAY['aphid'], ARRAY['powdery mildew'],
 'Excellent for wildlife and bees. Sow autumn for earliest spring flowers. Successive sow for long season.',
 'Shorter varieties (30–45cm) are sturdier in wind. Blue Ball, Blue Diadem for cutting.'),

-- CALENDULA
('Calendula', 'Calendula officinalis', 'annual', 'cut_flower',
 'Hardy annual, very easy to grow. Long flowering season. Medicinal and edible.',
 2, 3, 3, 5, 4, 5, 5, 10,
 4, 6,
 7, 14, 10, 18,
 20, 25, 1.0,
 30, 60,
 'full_sun', 'low', 'well-drained, any soil',
 'H5', true, false, 'low',
 true, 7, true, 4,
 ARRAY['tomato', 'asparagus', 'carrot', 'brassica'], ARRAY['none'],
 ARRAY['aphid', 'slugs'], ARRAY['powdery mildew'],
 'One of the easiest and most useful flowers. Self-seeds freely. Flowers edible in salads.',
 'Remove spent flowers to prolong blooming. Grows happily in poor soil. Excellent companion plant for repelling pests.'),

-- LARKSPUR
('Larkspur', 'Consolida ajacis', 'annual', 'cut_flower',
 'Tall, elegant annual. Direct sow in autumn or early spring. Doesn''t transplant well.',
 NULL, NULL, 3, 4, NULL, NULL, 5, 7,
 NULL, NULL,
 14, 21, 12, 18,
 20, 30, 0.5,
 60, 120,
 'full_sun', 'low', 'well-drained',
 'H5', true, false, 'low',
 true, 7, false, NULL,
 ARRAY['none'], ARRAY['none'],
 ARRAY['slugs', 'aphid'], ARRAY['powdery mildew'],
 'All parts toxic if eaten. Autumn sowing gives best plants — cold stratifies the seed. Excellent for wild-style gardens.',
 'Thinning is important — don''t let them crowd. Blue and white varieties very popular for weddings.'),

-- AMMI (White Lace Flower)
('Ammi', 'Ammi majus', 'annual', 'cut_flower',
 'White, frothy umbel — the florist''s favourite filler. Very popular for cutting.',
 2, 4, NULL, NULL, 4, 5, 6, 9,
 8, 12,
 14, 21, 12, 20,
 20, 30, 0.3,
 60, 90,
 'full_sun', 'low', 'well-drained, fertile',
 'H3', false, false, 'low',
 true, 7, false, NULL,
 ARRAY['none'], ARRAY['none'],
 ARRAY['aphid', 'carrot fly'], ARRAY['powdery mildew'],
 'Related to carrot — attracts the same pests. Surface sow — needs light to germinate. Pinch out for branching.',
 'Excellent as a filler with roses and dahlias. Harvest when 50% of flowers are open in the umbel.'),

-- SNAPDRAGON
('Snapdragon', 'Antirrhinum majus', 'annual', 'cut_flower',
 'Long-lasting cut flower. Many colours. Grows well in cool Irish summers.',
 1, 3, NULL, NULL, 4, 5, 6, 9,
 10, 12,
 14, 21, 15, 20,
 20, 25, 0.3,
 30, 90,
 'full_sun', 'medium', 'well-drained, fertile',
 'H3', true, false, 'medium',
 true, 10, false, NULL,
 ARRAY['none'], ARRAY['none'],
 ARRAY['aphid', 'slugs'], ARRAY['rust', 'downy mildew'],
 'Sow very early (January–February) in heat for best results. Surface sow — needs light.',
 'Pinch out growing tip when 10cm for bushier plant. Rocket series and Chantilly series excellent for cutting.');

-- ────────────────────────────────────────────────────────────
-- PERENNIALS
-- ────────────────────────────────────────────────────────────

INSERT INTO plants (
  name, latin_name, category, subcategory, description,
  sow_indoors_start, sow_indoors_end,
  transplant_start, transplant_end,
  harvest_start, harvest_end,
  weeks_indoors_min, weeks_indoors_max,
  germination_days_min, germination_days_max,
  germination_temp_min, germination_temp_max,
  spacing_cm, row_spacing_cm, sowing_depth_cm,
  height_cm_min, height_cm_max,
  sun_requirement, water_needs, soil_preference,
  hardiness_zone, frost_tolerant, frost_tender, slug_risk,
  is_perennial, lifespan_years, prune_month, divide_month,
  is_cut_flower, vase_life_days,
  companion_plants, avoid_near,
  common_pests, common_diseases,
  notes, growing_tips
) VALUES

-- ACHILLEA (Yarrow)
('Achillea', 'Achillea millefolium', 'perennial', 'cut_flower',
 'Excellent long-flowering perennial. Flat heads dry beautifully. Very tough in Irish conditions.',
 2, 4, 4, 5, 6, 9,
 10, 14,
 14, 21, 15, 25,
 30, 45, 0.3,
 60, 100,
 'full_sun', 'low', 'well-drained, any',
 'H7', true, false, 'low',
 true, NULL, 3, 3,
 true, 10,
 ARRAY['none'], ARRAY['none'],
 ARRAY['aphid'], ARRAY['powdery mildew'],
 'Very easy perennial once established. Divide every 3 years to keep vigorous. Flowers dry well for winter arrangements.',
 'Cerise Queen and Moonshine are classic varieties. Cut back hard in early spring.'),

-- ASTRANTIA
('Astrantia', 'Astrantia major', 'perennial', NULL,
 'Intricate, long-lived perennial perfect for cottage gardens and cutting.',
 2, 3, 4, 5, 5, 8,
 12, 16,
 21, 28, 15, 20,
 45, 45, 0.3,
 60, 90,
 'partial_shade', 'medium', 'moisture-retentive, humus-rich',
 'H6', true, false, 'medium',
 true, NULL, 3, 3,
 true, 7,
 ARRAY['fern', 'hosta'], ARRAY['none'],
 ARRAY['slugs'], ARRAY['powdery mildew'],
 'Thrives in partial shade with moist soil — ideal for sheltered Kildare gardens.',
 'Roma, Hadspen Blood, and Star of Billion are excellent varieties. Self-seeds but not invasively.'),

-- GERANIUM (Hardy Cranesbill)
('Hardy Geranium', 'Geranium spp.', 'perennial', NULL,
 'Incredibly reliable, low-maintenance perennial. Fills ground between shrubs beautifully.',
 2, 4, 4, 5, 5, 9,
 10, 14,
 21, 28, 15, 20,
 45, 60, 0.5,
 20, 60,
 'partial_shade', 'low', 'any well-drained',
 'H6', true, false, 'low',
 true, NULL, 3, 4,
 false, NULL,
 ARRAY['rose', 'salvia'], ARRAY['none'],
 ARRAY['vine weevil'], ARRAY['downy mildew'],
 'One of the best plants for Irish gardens. Tolerant of poor soil and partial shade. Cut back after first flush for repeat flowering.',
 'Rozanne is the classic long-flowering variety. G. phaeum (Mourning Widow) for deep shade.'),

-- SALVIA (Perennial)
('Salvia (Perennial)', 'Salvia nemorosa', 'perennial', NULL,
 'Long-flowering perennial salvia. Excellent for pollinators. Very reliable.',
 2, 4, 4, 5, 5, 9,
 10, 12,
 14, 21, 15, 20,
 30, 45, 0.3,
 45, 90,
 'full_sun', 'low', 'well-drained',
 'H5', true, false, 'low',
 true, NULL, 3, 4,
 false, NULL,
 ARRAY['rose', 'geranium', 'allium'], ARRAY['none'],
 ARRAY['vine weevil', 'capsid bug'], ARRAY['powdery mildew'],
 'Cut back hard after first flush for repeat flowering. Caradonna and Ostfriesland are reliable classics.',
 'Excellent for bees and butterflies. Very drought-tolerant once established. Grow in full sun for best flowering.'),

-- NEPETA (Catmint)
('Nepeta', 'Nepeta × faassenii', 'perennial', NULL,
 'Soft grey-green mounds with lavender flowers. Bees love it. Very easy in Irish gardens.',
 2, 4, 4, 5, 5, 9,
 10, 12,
 14, 21, 15, 20,
 45, 60, 0.3,
 30, 60,
 'full_sun', 'low', 'well-drained',
 'H6', true, false, 'low',
 true, NULL, 3, 4,
 false, NULL,
 ARRAY['rose', 'salvia'], ARRAY['none'],
 ARRAY['aphid', 'vine weevil'], ARRAY['powdery mildew'],
 'Walker''s Low and Six Hills Giant are excellent varieties. Shear back after first flowering for second flush.',
 'Classic edging plant for borders. Cats may roll in it.'),

-- VERBENA BONARIENSIS
('Verbena bonariensis', 'Verbena bonariensis', 'perennial', NULL,
 'Tall, airy perennial with purple pom-pom flowers. Self-seeds freely. Superb for wildlife.',
 2, 3, 4, 5, 6, 10,
 10, 14,
 14, 21, 15, 22,
 45, 60, 0.3,
 120, 180,
 'full_sun', 'low', 'well-drained',
 'H4', true, false, 'low',
 true, NULL, 3, NULL,
 false, NULL,
 ARRAY['dahlia', 'salvia', 'ornamental_grass'], ARRAY['none'],
 ARRAY['aphid'], ARRAY['powdery mildew'],
 'Short-lived perennial but self-seeds prolifically. Transparent plant — looks great weaving through others.',
 'Usually treated as annual in colder parts of Ireland. Grow through shrubs for best effect. Butterfly magnet.'),

-- ECHINACEA (Coneflower)
('Echinacea', 'Echinacea purpurea', 'perennial', 'cut_flower',
 'Bold prairie perennial with long-lasting flowers. Attracts birds to seed heads in winter.',
 2, 4, 4, 5, 7, 9,
 12, 16,
 21, 28, 18, 25,
 45, 60, 0.3,
 60, 120,
 'full_sun', 'low', 'well-drained',
 'H5', true, false, 'low',
 true, NULL, 3, 4,
 true, 7,
 ARRAY['rudbeckia', 'salvia', 'grasses'], ARRAY['none'],
 ARRAY['slugs', 'vine weevil'], ARRAY['aster yellows'],
 'Slow to establish but long-lived once settled. Magnus and White Swan are reliable varieties.',
 'Leave seed heads for birds over winter. Divide every 4–5 years in spring.'),

-- HELENIUM
('Helenium', 'Helenium autumnale', 'perennial', 'cut_flower',
 'Brilliant late summer and autumn colour. Very good for cutting. Bees adore it.',
 2, 4, 4, 5, 7, 10,
 10, 14,
 14, 21, 15, 20,
 45, 60, 0.3,
 60, 120,
 'full_sun', 'medium', 'moisture-retentive, fertile',
 'H6', true, false, 'low',
 true, NULL, 3, 3,
 true, 7,
 ARRAY['rudbeckia', 'echinacea'], ARRAY['none'],
 ARRAY['aphid', 'vine weevil'], ARRAY['powdery mildew'],
 'Chelsea chop (cut back by half in late May) delays flowering and prevents flopping.',
 'Moerheim Beauty and Sahin''s Early Flowerer excellent varieties. Divide every 3 years to maintain vigour.');

-- Add an index by name for search
CREATE INDEX IF NOT EXISTS idx_plants_name_search ON plants USING gin(to_tsvector('english', name));
